//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TZ_1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Addresses
    {
        public long Id { get; set; }
        public Nullable<long> Coutry { get; set; }
        public Nullable<long> City { get; set; }
        public Nullable<long> Street { get; set; }
        public Nullable<int> House { get; set; }
        public Nullable<long> Indeks { get; set; }
        public Nullable<System.DateTime> Data { get; set; }
    
        public virtual City City1 { get; set; }
        public virtual Country Country { get; set; }
        public virtual Street Street1 { get; set; }
    }
}
